### PR TITLE
Article search bar

### PR DESCRIPTION
**Pull request by sirlilpanda**
Added a search bar for quickly finding the desired article, the search is currently searches for the keyword within the title, description and slug. below is an image of the search bar:
image
image

the search bar expands when is in focus to make it easier to see what you are typing. When typing the top 5 articles ordered on date that match the search will appear below and when not searching all articles will appear. To the right of the search part there is a clear button that will clear the current search from the input.

### CODE REVIEW

**Review by JHay0112 — CHANGES_REQUESTED** [review]
The drop shadow and styling in the light theme are quite jarring. They need refinement before they are included. Search functionality looks good otherwise.

image

**Comment by sirlilpanda** [comment]
the drop shadow was added so there is a clearer outline of where the search box actually is. As can be seen below if there is no box shadow around its hard to see where to click to enter text in to the search bar. 
image

but with the shadow the outline of the input field can be clearly seen making it easier to click on.
image

**Comment by JHay0112** [comment]
I agree that the box shouldn't blend in. But the drop shadow as it is isn't consistent with the look and feel of the rest of the website. I think that either it should be more subtle or the background of the box should be changed to contrast with the page background.

**Comment by JHay0112** [comment]
Here's a version where the background of the search bar matches the header colour.

image

image

I think this has a more consistent look and feel than the drop shadow. The only other drop shadow use I can see immediately on the site is when hovering over clickable items. We could do something similar for the search bar if you feel this needs a similar call out?

**Comment by sirlilpanda** [comment]
search bar now has a smaller box shadow with a different background colour.

image

**Review by JHay0112 — APPROVED** [review]

**Pull request merged**
